import type { ProductTypeId } from "./pricing";

export type ReadyProduct = {
  id: string;
  name: string;
  tagline: string;
  designId: string;
  colorId: string;
  colorHex: string;
  colorLabel: string;
  productType: ProductTypeId;
  price: number;
  mrp: number;
  badge?: "Best Seller" | "New Arrival" | "Trending" | "Limited";
};

export const READY_PRODUCTS: ReadyProduct[] = [
  {
    id: "rp-beast-black",
    name: "Beast Mode Tee",
    tagline: "For the grind that never stops",
    designId: "fit-1",
    colorId: "black",
    colorHex: "#171717",
    colorLabel: "Black",
    productType: "round",
    price: 399,
    mrp: 499,
    badge: "Best Seller",
  },
  {
    id: "rp-mountain-white",
    name: "Mountain Minimal Tee",
    tagline: "Clean lines. Big dreams.",
    designId: "min-1",
    colorId: "white",
    colorHex: "#f5f5f5",
    colorLabel: "White",
    productType: "round",
    price: 449,
    mrp: 549,
    badge: "New Arrival",
  },
  {
    id: "rp-404-navy",
    name: "404 Sleep Tee",
    tagline: "For every late-night coder",
    designId: "tf-1",
    colorId: "navy",
    colorHex: "#1e3a5f",
    colorLabel: "Navy Blue",
    productType: "round",
    price: 449,
    mrp: 549,
    badge: "Best Seller",
  },
  {
    id: "rp-bengaluru-black",
    name: "Bengaluru Pride Tee",
    tagline: "Namma city, namma pride",
    designId: "kn-1",
    colorId: "black",
    colorHex: "#171717",
    colorLabel: "Black",
    productType: "round",
    price: 499,
    mrp: 599,
    badge: "Trending",
  },
  {
    id: "rp-born-green",
    name: "Born to Code Tee",
    tagline: "Where logic meets lifestyle",
    designId: "tf-4",
    colorId: "green",
    colorHex: "#166534",
    colorLabel: "Forest Green",
    productType: "round",
    price: 449,
    mrp: 549,
    badge: "New Arrival",
  },
  {
    id: "rp-cricket-navy",
    name: "Straight Drive Tee",
    tagline: "Play hard. Look sharp.",
    designId: "cr-1",
    colorId: "navy",
    colorHex: "#1e3a5f",
    colorLabel: "Navy Blue",
    productType: "round",
    price: 399,
    mrp: 499,
    badge: "Trending",
  },
  {
    id: "rp-nopain-red",
    name: "No Pain No Gain Tee",
    tagline: "Pain is temporary, glory is forever",
    designId: "fit-2",
    colorId: "red",
    colorHex: "#b91c1c",
    colorLabel: "Red",
    productType: "round",
    price: 399,
    mrp: 499,
  },
  {
    id: "rp-wave-white",
    name: "Simple Wave Tee",
    tagline: "Minimal. Everyday. Perfect.",
    designId: "min-2",
    colorId: "white",
    colorHex: "#f5f5f5",
    colorLabel: "White",
    productType: "round",
    price: 449,
    mrp: 549,
  },
  {
    id: "rp-ctrl-grey",
    name: "Ctrl Alt Delete Tee",
    tagline: "Reset. Reboot. Repeat.",
    designId: "tf-5",
    colorId: "grey",
    colorHex: "#9ca3af",
    colorLabel: "Grey",
    productType: "round",
    price: 399,
    mrp: 499,
  },
  {
    id: "rp-namma-black",
    name: "Namma Karnataka Tee",
    tagline: "Wear your roots with pride",
    designId: "kn-2",
    colorId: "black",
    colorHex: "#171717",
    colorLabel: "Black",
    productType: "round",
    price: 449,
    mrp: 549,
    badge: "Limited",
  },
];
